# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build SpringBoot Project with Maven

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Creating docker image
      uses: cloudposse/github-action-docker-build-push@1.12.0
      with:
        registry: docker.io
        # Image name (excluding registry). Defaults to {{$organization/$repository}}.
        image_name: makdocr/springboot-app
        # Docker login
        login: ${{ secrets.DOCKER_USERNAME }}
        # Docker password
        password: ${{ secrets.DOCKER_PASSWORD }}
